version: "2"
linters:
  default: all
  disable:
    - wsl_v5
    - wsl
    - testpackage
    - paralleltest
    - depguard
    - funlen
    - mnd
    - wrapcheck
    - varnamelen
    - gochecknoglobals
    - exhaustruct
    - exhaustive
    - gocritic
    - cyclop
  exclusions:
    rules:
      - linters:
          - revive
        text: be unexported
      - linters:
          - revive
        text: package comment
      - linters:
          - revive
        text: meaningless package names
      - linters:
          - revive
        text: comment on exported
      - linters:
          - revive
          - err113
        path: _test\.go
      - linters:
          - gosec
        text: weak random number
      - linters:
          - err113
        text: do not define dynamic errors
      - linters:
          - ireturn
        text: returns generic interface
